server:
  port: 8080

spring:
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://eureka-service:8761/eureka/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movieRoute
          uri: lb://MOVIE-SERVICE:8081
          predicates:
            - Path=/movie/**
          filters:
            - name: CircuitBreaker
              args:
                name: movieService
                fallbackUri: forward:/fallback/movie
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE:8082
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

queue:
  movie:
    name: movieQueue


