eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Rener Almeida
  mail: wouldntyouliketoknow@blablabla.com
server:
  port: ${PORT:9999}
message: Generic
