server:
  port: 8081
  servlet:
    context-path: /movie/

spring:
  application:
    name: movie-service
  zipkin:
    base-url: http://zipkin-service:9411/
  config:
    import: optional:configserver:http://config-service:8888
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: movie_user
#    password: 1234
#    url: jdbc:mysql://movie_db:3306/movie_db?createDatabaseIfNotExist=true
#    jpa:
#      properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
#      hibernate.ddl-auto: update
#      generate-ddl: true
#      show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: movieQueue

message: Movie up

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Micro serviço de filmes
  author: Rener Almeida
  severity: Alto
